### ISSUE TITLE
eval.py doesn't work with python2

### ISSUE THREAD

**Issue by thebaptiste** [metwork-framework/mfutil#18]
Because functools.partialmethod doesn't exist in python2 and we can't use functools.partial on `__init__` function (if we do so, test_eval.py returns the following error) : 
```
s = SandboxedEval(names=variables)
TypeError: unbound method __init__() must be called with _Eval instance as first argument (got nothing instead)
```
The tests on eval.py in test_eval.py have been bypassed (remove the test on `sys.version` in this file if you have to work on the current issue)

**Comment by thefab** [comment]
now we have some python3 only code in mfutil
we give up on this
